language: java

sudo: false

jdk:
- openjdk8
- openjdk10
- oraclejdk8
- oraclejdk10

notifications:
  email: false

branches:
  only:
    - master

install:
  - ./mvnw clean install -B -V -DskipTests=true -Dmaven.test.skip=true -Dmaven.javadoc.skip=true

script:
  - ./mvnw verify -Droot.logging.level=INFO

after_success:
  - ./mvnw jacoco:report coveralls:report
  - bin/ci-push-javadoc.sh
  - bin/ci-deploy-snapshot.sh